### ISSUE TITLE
The program does not run, and the example usage demo is missing

### ISSUE THREAD

**Issue by Danjuanlab** [nullmastermind/node-autoit-napi#1]
![image](https://github.com/nullmastermind/node-autoit-napi/assets/42509669/2d3e9d14-0868-443c-b68b-2af67f4ec622)

**Comment by yuanquan8** [comment]
俺也一样

**Comment by Maksbjj** [comment]
I'm facing the same issue 
@nullmastermind is there any chance you could take a look on that? 
Thx

**Comment by nullmastermind** [comment]
@Maksbjj, of course, I will fix it soon within 1-2 working days. (Other information: The old Node.js version is still working well.)

**Comment by nullmastermind** [comment]
@yuanquan8 @Danjuanlab @Maksbjj https://www.npmjs.com/package/node-autoit-koffi A gift for you all
